"""Initial migration

Revision ID: 87e225cfab7e
Revises: 
Create Date: 2026-01-21 04:39:33.491078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '87e225cfab7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key and unique identifier for the profile'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Full name of the user'),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address (must be unique)"),
    sa.Column('title', sa.String(length=200), nullable=True, comment='Professional title or headline'),
    sa.Column('location', sa.String(length=200), nullable=True, comment="User's current location"),
    sa.Column('about', sa.Text(), nullable=True, comment='Detailed bio or about information in markdown format'),
    sa.Column('github_url', sa.String(length=500), nullable=True, comment="URL to the user's GitHub profile"),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True, comment="URL to the user's LinkedIn profile"),
    sa.Column('twitter_url', sa.String(length=500), nullable=True, comment="URL to the user's Twitter/X profile"),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True, comment="URL to the user's profile picture"),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Additional metadata in JSON format'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when the profile was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when the profile was last updated'),
    sa.PrimaryKeyConstraint('id'),
    comment='Stores user profile information',
    postgresql_partition_by='HASH (id)'
    )
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_index(op.f('ix_profiles_location'), 'profiles', ['location'], unique=False)
    op.create_index(op.f('ix_profiles_name'), 'profiles', ['name'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('demo_url', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_is_featured'), 'projects', ['is_featured'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_featured'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_profiles_name'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_location'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
